experiment_name: gru_experiment_20251009_153924
run_timestamp: '20251009_153924'

data:
  data_dir: /home/nigel/git/MLR_working_party/01_data/
  filename: data_origframework_nofills_nosttl.csv
  cutoff: 40
  cutoff1: 32
  maxdev: 40
  data_cols:
  - occurrence_time
  - notidel
  - development_period
  - pmt_no
  - log1_paid_cumulative
  - claim_no
  features:
  - occurrence_time
  - notidel
  - development_period
  - pmt_no
  - log1_paid_cumulative
  output_field: claim_size

model:
  batch_norm: false
  clip_value: null
  device: cpu
  dropout: 0.0
  keep_best_model: false
  l1_applies_params:
  - linear.weight
  - hidden.weight
  l1_penalty: 0.0
  max_lr: 0.01
  n_hidden: 32
  n_output: 1
  weight_decay: 0.0

training:
  cv_runs: 24
  enable_shap: true
  glm_iter: 500
  mdn_iter: 1000
  nn_cv_iter: 100
  nn_iter: 2001
  print_loss_every_iter: 100
  rebatch_every_iter: 1
  shap_background_samples: 100
  shap_log_frequency: 500
  shap_max_samples: 50
  verbose: 1

tensorboard:
  log_metrics_every: 1
  log_figures_every: 100
  log_gradients: true
  log_weights_histograms: true
  log_shap_explanations: true
  shap_log_frequency: 500
