experiment_name: gru_experiment_20251009_153924
run_timestamp: '20251009_153924'

data:
  data_dir: https://raw.githubusercontent.com/agi-lab/SPLICE/main/datasets/complexity_1/
  filename: payment_1.csv
  dataset_no: 1
  cutoff: 40
  
  maxdev: 40
  data_cols:
  - notidel
  - occurrence_time
  - development_period
  - payment_period
  - has_payment_to_prior_period 
  - log1_payment_to_prior_period
  - payment_count_to_prior_period

  features:
  - notidel
  - occurrence_time
  - development_period
  - payment_period
  - has_payment_to_prior_period
  - log1_payment_to_prior_period
  - payment_count_to_prior_period
  - backdate_periods
  
  output_field: payment_size

model:
  batch_norm: false
  clip_value: null
  device: cpu
  dropout: 0.0
  keep_best_model: false
  l1_applies_params:
  - linear.weight
  - hidden.weight
  l1_penalty: 0.0
  max_lr: 0.01
  n_hidden: 32
  n_output: 1
  weight_decay: 0.0

training:
  seed: 42
  cv_runs: 4
  enable_shap: true
  mdn_iter: 500
  nn_cv_iter: 200
  nn_iter: 1200
  print_loss_every_iter: 10
  rebatch_every_iter: 1
  shap_background_samples: 100
  shap_log_frequency: 240
  shap_max_samples: 100
  verbose: 1

tensorboard:
  log_metrics_every: 1
  log_figures_every: 20
  log_gradients: true
  log_weights_histograms: true
  log_shap_explanations: true
  shap_log_frequency: 240
